# Example configuration for training the trajectory transformer.
# Update the CSV and GeoJSON paths to match your environment.

data:
  csv_path: data/data.csv
  geojson_path: data/landmask.geojson
  history_window: 12
  forecast_horizon_minutes: 60
  sample_rate_minutes: 10
  cluster_destinations: true
  destination_cluster_count: 64
  minimum_track_length: 24
  validation_fraction: 0.1
  test_fraction: 0.1
  random_seed: 42

model:
  input_dim: 12
  static_feature_dim: 16
  hidden_dim: 256
  ff_dim: 512
  num_heads: 8
  num_layers: 6
  dropout: 0.1
  predict_steps: 6
  num_destination_clusters: 64
  destination_loss_weight: 0.5
  land_penalty_weight: 5.0
  geodesic_loss_weight: 1.0
  velocity_loss_weight: 0.3
  predict_speed: true
  predict_heading: true

training:
  batch_size: 128
  num_epochs: 50
  learning_rate: 3.0e-4
  weight_decay: 1.0e-4
  lr_scheduler: cosine
  gradient_clip_norm: 1.0
  max_grad_norm: 1.0
  mixed_precision: true
  num_workers: 4
